# Generated by Django 5.2.5 on 2025-08-31 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('perplexity', 'Perplexity'), ('xai', 'xAI')], max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_content_type', models.CharField(max_length=50)),
                ('source_content_url', models.URLField(blank=True, max_length=500, null=True)),
                ('task_prompt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_per_token_input', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('cost_per_token_output', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('supported_modalities', models.JSONField(default=list)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='myapi.aiprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(max_length=50)),
                ('tokens_used', models.IntegerField()),
                ('time_taken_seconds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_usd', models.DecimalField(decimal_places=5, max_digits=10)),
                ('accuracy_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='myapi.experiment')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.aimodel')),
            ],
        ),
    ]
