# Generated by Django 5.2.5 on 2025-08-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='cost_per_token_input',
            new_name='cost_per_token_text',
        ),
        migrations.RenameField(
            model_name='aimodel',
            old_name='cost_per_token_output',
            new_name='cost_per_token_video',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='cost_per_token_audio',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='cost_per_token_doc',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='cost_per_token_image',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
